### ISSUE TITLE
Question for the developers.

### ISSUE THREAD

**Issue by ozturkkl** [xtk93x/Leaflet.TileLayer.ColorFilter#5]
Thank you for this awesome plugin!

I am a University of Cincinnati student. I would like to use this to do the exact same filtering for my custom marker icons.
- Am I allowed to use this code? 
- Is it possible for a newbie like me to do such things? 

I am not an experienced developer. Could you please point me in the right direction.
What I want to do --> An option for markers that enable filtering their icons just like this code filtering title layers.

I am amazed by how a short amount of code like this can accomplish a lot of filtering. 😍
I hope to improve my skills and be able to create stuff like this in the future.

Thank you again for your time and awesome plugin!
Kemal

**Comment by xtk93x** [comment]
Hi! First of all, thank you so much for the kind feedback. It makes me really glad that this project is being useful. Since I am a data scientist, I didn't play with frontend code for a while. But I will do my best to explain. So, answering your questions:

- Yes, definitely feel free to use the code!
- Yes, but I recommend you to learn it step by step. When you see the final version plugin, even with just a few lines of code, it may seem a bit confusing. So I will try to point some directions to help your learning.

The key thing to understand is how we are changing the color of things here. [See this article](https://developer.mozilla.org/en-US/docs/Web/CSS/filter). You can change the color of any element (your custom markers for example :smiley:). 

We can apply any of those filters using javascript by accessing the `.style.filter` property of an element. Paste this code in any `.html` file and open it with your browser. In this example, I am adding the grayscale in the `_container` of the tile layer. If you open the browser console, you can inspect the entire tile layer object printed by the console log (you can use something similar to inspect your marker object).

```js
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.4/leaflet.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.4/leaflet.js"></script>
    <style>
        #map-default {
            height: 100%;
            width: 100%;
        }
    </style>
</head>

<body>
        <div id="map-default"></div>
</body>

<script>
    var defaultMap = L.map('map-default').setView([51.505, -0.09], 14);

    var myLayer = L.tileLayer('https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png', {
        attribution: '<a href="https://wikimediafoundation.org/wiki/Maps_Terms_of_Use">Wikimedia</a>',
    });

    myLayer.addTo(defaultMap)

    console.log(myLayer)

    myLayer._container.style.filter = "grayscale(100%)" // <- it is all about this line
</script>
```

Pretty simple, right? Most part of the original plugin is just parsing strings and options. The important part is just the line 27 of the code above.

Use this code as a sandbox to put markers and change its color! I have the answer here, but I will let you find out.

The next step would be transforming this into a plugin. For this, knowledge about how Leaflet and javascript/html/css work is required. I learned by reading the code and playing with it. Then, I knew exactly what functions I should encapsulate (making Leaflet tile layer to call my custom function first, which applies the color filer and only then it calls the actual Leaflet function). Maybe at this moment, it will be a little bit hard to understand. But with experience, it gets easier, and we can also learn a lot of good practices reading their code.

**Mail me if you have progress or more questions, I will be happy to see the results!**

Good luck.

**Comment by ozturkkl** [comment]
Thank you so much for taking your time and replying!

I have a pretty good idea now how I will approach this, I will post here the end result of my little experiment when I am done. I would love to get feedback and improve it further with your insight.

Again, thanks for your time. 🙏😊

**Comment by xtk93x** [comment]
Awesome! Thank you too, and good luck! :smiley:

**Comment by ozturkkl** [comment]
I think I am happy with the end result, it is more than I need in my project.
I am grateful for your guidance and support. 🙏🙏

Here is the demo to what I have done so far: [Marker.ColorFilter-demo](https://ozturkkl.github.io/Leaflet.Marker.ColorFilter/demo/)

**Comment by xtk93x** [comment]
Great job!! 😄
